const API_URL='https://script.google.com/macros/s/AKfycbwU7DXGgMMWj1UqWtl2Izap8a8Bg7ulRIwgRssqIW9IXhdDMNATTNIaDlpC2-aN4GXw/exec';
const state={program:null,checklist:[],risk:[],legal:[],responses:{},current:null,meta:{}};
const $=x=>document.getElementById(x); const views=['home','audit','summary'];
function show(id){views.forEach(v=>$(v)?.classList.toggle('hidden',v!==id))}
function uid(){return crypto.randomUUID?crypto.randomUUID():'id-'+Date.now()+'-'+Math.random().toString(16).slice(2)}
async function init(){state.risk=await fetch('risk-master.json').then(r=>r.json());state.legal=await fetch('legal-master.json').then(r=>r.json());document.querySelectorAll('[data-program]').forEach(b=>b.onclick=()=>openProgram(b.dataset.program));$('backHome').onclick=()=>show('home');$('saveBtn').onclick=saveDraft;$('closeFinding').onclick=closeFinding;$('saveFinding').onclick=saveFinding;document.querySelectorAll('[data-st]').forEach(b=>b.onclick=()=>setStatus(b.dataset.st));$('duePreset').onchange=calcDue;window.addEventListener('online',net);window.addEventListener('offline',net);net();registerSW();installPrompt();loadDraftInfo()}
async function openProgram(p){if(p!=='MeSTI'){alert(p+' module belum dimasukkan ke master checklist. Struktur app sudah bersedia.');return} state.program=p;state.checklist=await fetch('mesti-checklist.json').then(r=>r.json());loadDraft();$('programTitle').textContent=p;$('tarikh').value=$('tarikh').value||new Date().toISOString().slice(0,10);renderSections();show('audit')}
function renderSections(){const groups={};state.checklist.forEach(q=>(groups[q.section]??=[]).push(q));$('sections').innerHTML=Object.entries(groups).map(([s,qs])=>`<section class="section"><button class="sectionhead" onclick="toggleSec('${s}')"><span>${s}. ${qs[0].section_name}</span><span id="sc${s}">${secDone(qs)}</span></button><div class="sectionbody hidden" id="sec${s}">${qs.map(q=>qHtml(q)).join('')}</div></section>`).join('')+`<div class="card"><button onclick="showSummary()">Lihat Rumusan Risk-Based →</button></div>`;updateProgress()}
window.toggleSec=s=>$('sec'+s).classList.toggle('hidden');
function qHtml(q){const r=state.responses[q.id]||{};return `<div class="qitem" onclick="openFinding('${q.id}')"><div class="code">${q.code}</div><div>${esc(q.question)}</div><div class="qstatus">${r.status||'Belum dinilai'}${r.demerit?` • Demerit ${r.demerit}`:''}</div></div>`}
function secDone(qs){const n=qs.filter(q=>state.responses[q.id]?.status).length;return `${n}/${qs.length}`}
window.openFinding=id=>{state.current=state.checklist.find(q=>q.id===id);const r=state.responses[id]||{};$('findingCode').textContent=state.current.code;$('findingQ').textContent=state.current.question;$('findingNote').value=r.note||'';$('riskSelect').innerHTML='<option value="">-- pilih jika berkaitan --</option>'+state.risk.map(x=>`<option value="${x.risk_id}" ${r.risk_id===x.risk_id?'selected':''}>${x.risk_id} • ${x.domain} • ${x.demerit} markah</option>`).join('');$('legalSelect').innerHTML=state.legal.map(x=>`<option value="${x.reg}" ${(r.legal||[]).includes(x.reg)?'selected':''}>Per. ${x.reg} — ${x.title}</option>`).join('');$('directiveType').value=r.directiveType||'Teguran';$('directiveText').value=r.directiveText||'';$('dueDate').value=r.dueDate||'';$('followDate').value=r.followDate||'';$('section10').checked=!!r.section10;$('npBlock').classList.toggle('hidden',r.status!=='Tidak Patuh');$('finding').classList.remove('hidden')}
function closeFinding(){$('finding').classList.add('hidden');state.current=null}
function setStatus(st){if(!state.current)return;const r=state.responses[state.current.id]||{};r.status=st;state.responses[state.current.id]=r;$('npBlock').classList.toggle('hidden',st!=='Tidak Patuh')}
function calcDue(){const v=$('duePreset').value;if(v==='custom')return;const d=new Date();d.setDate(d.getDate()+Number(v));$('dueDate').value=d.toISOString().slice(0,10)}
function saveFinding(){if(!state.current)return;const r=state.responses[state.current.id]||{};r.note=$('findingNote').value;if(r.status==='Tidak Patuh'){r.risk_id=$('riskSelect').value;const rr=state.risk.find(x=>x.risk_id===r.risk_id);r.demerit=rr?.demerit||0;r.legal=[...$('legalSelect').selectedOptions].map(o=>o.value);r.directiveType=$('directiveType').value;r.directiveText=$('directiveText').value;r.dueDate=$('dueDate').value;r.followDate=$('followDate').value;r.section10=$('section10').checked;r.directive_id=r.directive_id||uid()}else{delete r.risk_id;delete r.demerit}state.responses[state.current.id]=r;saveDraft();closeFinding();renderSections()}
function captureMeta(){state.meta={premis:$('premis').value,tarikh:$('tarikh').value,auditor:$('auditor').value,jenis:$('jenis').value,audit_id:state.meta.audit_id||uid(),program:state.program}}
function saveDraft(){captureMeta();localStorage.setItem('IHK_AUDIT_DRAFT',JSON.stringify({meta:state.meta,responses:state.responses}));loadDraftInfo();alert('Draf disimpan pada peranti. Sync backend boleh diaktifkan selepas API URL dimasukkan.')}
function loadDraft(){const d=JSON.parse(localStorage.getItem('IHK_AUDIT_DRAFT')||'null');if(!d||d.meta?.program!==state.program)return;state.meta=d.meta||{};state.responses=d.responses||{};$('premis').value=state.meta.premis||'';$('tarikh').value=state.meta.tarikh||'';$('auditor').value=state.meta.auditor||'';$('jenis').value=state.meta.jenis||'Rutin'}
function loadDraftInfo(){const d=JSON.parse(localStorage.getItem('IHK_AUDIT_DRAFT')||'null');$('draftInfo').textContent=d?`${d.meta?.program||'-'} • ${d.meta?.premis||'Premis belum diisi'} • ${d.meta?.tarikh||'-'}`:'Tiada draf.'}
function updateProgress(){const done=state.checklist.filter(q=>state.responses[q.id]?.status).length,p=state.checklist.length?Math.round(done/state.checklist.length*100):0;$('progressText').textContent=`${done}/${state.checklist.length} item • ${p}%`;$('progressBar').style.width=p+'%'}
window.showSummary=()=>{captureMeta();const np=Object.entries(state.responses).filter(([,r])=>r.status==='Tidak Patuh');const dem=np.reduce((a,[,r])=>a+(r.demerit||0),0);const legal=[...new Set(np.flatMap(([,r])=>r.legal||[]))];$('summary').innerHTML=`<div class="toprow"><button class="light" onclick="show('audit')">← Audit</button><h2>Rumusan ${state.program}</h2></div><div class="card"><h3>${esc(state.meta.premis||'-')}</h3><p>Item tidak patuh: <b>${np.length}</b></p><p>Jumlah demerit dipilih: <b>${dem}</b></p><p>Rujukan PPKM berpotensi: <b>${legal.map(x=>'Per. '+x).join(', ')||'-'}</b></p><p class="muted">Rujukan undang-undang memerlukan pengesahan pegawai sebelum tindakan penguatkuasaan.</p></div><div class="card"><h3>Arahan/Teguran Aktif</h3>${np.map(([id,r])=>{let q=state.checklist.find(x=>x.id===id);return `<div class="qitem"><b>${q.code}</b> • ${r.directiveType||'Teguran'}<br>${esc(r.directiveText||r.note||'')}<br><small>Tarikh akhir: ${r.dueDate||'-'} • Susulan: ${r.followDate||'-'}</small></div>`}).join('')||'Tiada.'}</div>`;show('summary')}
function net(){$('net').textContent=navigator.onLine?'● online':'● offline'}
function registerSW(){if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js')}
let deferred;function installPrompt(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('installBtn').hidden=false});$('installBtn').onclick=async()=>{if(!deferred)return;deferred.prompt();await deferred.userChoice;deferred=null;$('installBtn').hidden=true}}
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
init();
