window.IHK_CONFIG = {
  APP_NAME: 'IHK Audit PWA',
  VERSION: '3.0.0',
  API_URL: 'PASTE_YOUR_APPS_SCRIPT_WEB_APP_URL_HERE',
  SHEET_ID: '1Ho4wU1qV6NmvQ3ygb1Q4NXoGjjFr6ePNsK068vlN-ho',
  DRIVE_FOLDER_ID: '1_qUWg7W4i8XEkUI7gui-TvjdHrrV65es',
  ENABLE_REMOTE_DASHBOARD: true
};
